file(WRITE "${CXX_FILE}" "")
file(READ "${CL_FILE}" CL_CODE)
string(REGEX REPLACE "\\\\" "\\\\\\\\" CL_CODE "${CL_CODE}")
string(REGEX REPLACE "\n"   "\\\\\n"   CL_CODE "${CL_CODE}")
string(REGEX REPLACE "\n"   "\\n\\\\n" CL_CODE "${CL_CODE}")
string(REGEX REPLACE "\""   "\\\\\""   CL_CODE "${CL_CODE}")
file(APPEND "${CXX_FILE}"   "static const char* src = \"\\\n")
file(APPEND "${CXX_FILE}"   "${CL_CODE}\";\n\n")
file(APPEND "${CXX_FILE}"   "#include <utility/oskar_cl_registrar.h>\n")
file(APPEND "${CXX_FILE}"   "OSKAR_CL_SRC(src)\n")
