include(${OSKAR_SOURCE_DIR}/cmake/oskar_build_macros.cmake)
get_svn_revision(${OSKAR_SOURCE_DIR} svn_revision)
file(REMOVE ${OSKAR_SOURCE_DIR}/version.txt)
if (svn_revision)
    file(WRITE ${OSKAR_SOURCE_DIR}/version.txt "OSKAR ${VERSION}")
endif()
